apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-np
  template:
    metadata:
      labels:
        app: my-app-np
    spec:
      containers:
      - name: my-container
        image: vijaygiduthuri/netflix:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-svc
  labels:
    app: my-app-np
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 80
    protocol: TCP
    nodePort: 32080
  selector:
    app: my-app-np
